name: Windows GNU

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        platform:
          - windows-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-gnu-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-gnu-cargo-index-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          target: "x86_64-pc-windows-gnu"
      - name: "Test on x86_64-pc-windows-gnu"
        run: cargo test --all-features
